title: Francis Gichere # your name (or website title) here
logo: "/images/DSC_0031 (3).png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist || Data Analyst
  <br><br>
  A data scientist who takes pride in research, data analysis, data visualization, and in building Machine Learning models using that translate data points into insights.
  Used my skills in my first research paper (Published), in a startup business as a business analyst, and as a freelance data analyst. 
  <br><br>
  <a href="https://www.linkedin.com/in/francis-kuira-gichere-436814a0/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://http://www.ijern.com/journal/2019/January-2019/02.pdf/">View My Published Research paper</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
