title: FRANCIS GICHERE # your name (or website title) here
logo: "/images/DSC_0031 (3).jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Data Scientist || Data Analyst
  <br><br>
  An entry-level data scientist who takes pride in research, data analysis, data visualization, and in building Machine Learning models that translate data points into insights. Used my skills in my first research paper (Published), in a startup business as a business analyst, and as a freelance data analyst.
  <br><br>
  <a href="https://www.linkedin.com/in/francis-kuira-gichere-436814a0/">View My LinkedIn Profile</a> 
  
theme: 
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
